language: go

go:
  - 1.9.x

before_install:
  - go get -t -v ./...
  - curl -s -o video.mp4 $TGWRAP_DOWNLOAD_URL_VIDEO

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - curl -s -o video.mp4 $TGWRAP_DOWNLOAD_URL_VIDEO

after_success:
  - bash <(curl -s https://codecov.io/bash)